### ISSUE TITLE
fix:알림 테스트

### ISSUE THREAD

**Issue by zxcv2987** [woomae/copet#109]
### 🐞 Description
- 클라이언트단에서 알림 수신 처리 로직은 구현되어있음.
![image](https://github.com/user-attachments/assets/e974d261-948d-4efb-ac0f-4d1187cdb02d)
- 화면과 같이 messaging/invalid-payload 오류가 뜨지만, 데이터베이스엔 친구 추가나 게시글 좋아요 적용은 됨.
- 적용은 되지만 알림은 안 온답니다..

### 🧐 How to Solve?
- 알림 트리거는 기능하지만 토큰을 못찾거나 하는 것 같음. 한 번 확인해주세요
### 👥 Assignees
_<sub>@woonae</sub>_

**Comment by woomae** [comment]
현재 서버 데이터베이스에 작성된 제 User컬럼은 디바이스토큰값이 없습니다. 따라서 알람트리거는 작동하지 않을 것입니다.
해결을 위해서는 디바이스 토큰 추가 저장이 필요합니다.
