### ISSUE TITLE
fix:게시글 이미지 수정

### ISSUE THREAD

**Issue by zxcv2987** [woomae/copet#110]
### 🐞 Description
- 게시글 수정 api 명서세 사진에 나온것과 동일하게 전송했는데도  "\"article\" alias was not found. 오류 뜨네요
- 썬더 클라이언트, 로컬 디바이스 기기 테스트 둘 다 같은 오류 뜹니다
![image](https://github.com/user-attachments/assets/71353927-0b58-4b1c-89e8-6bb76b1b9d35)

### 👥 Assignees
_<sub>@woomae</sub>_

**Comment by woomae** [comment]
확인중입니다.

**Comment by woomae** [comment]
서버 함수 오타로 인해 발생하던 오류였습니다.
오타수정 완료해서 서버 재배포 했습니다.
