### ISSUE TITLE
fix: 최근 검색어 삭제

### ISSUE THREAD

**Issue by zxcv2987** [woomae/copet#111]
### 🐞 Description
_ 최근 검색어 삭제 api 실행 시 코드 200 잘 나오는데 다시 최근 검색어 get 요청 때려보면 삭제가 되어있지 않습니다.
![image](https://github.com/user-attachments/assets/5a14e091-d1bb-4254-ae09-768103ebc83e)

### 🧐 How to Solve?
- _최근 검색어 삭제 api에 오탈자는 없는지 한 번 확인해 주세요._

### 👥 Assignees
_<sub>(@woomae )</sub>_

바쁘시겠지만 화이팅입니다

**Comment by woomae** [comment]
API명세에 보시면 파라미터 옵션있는데 넣지않은것 같습니다.
서버에서 정상작동됩니다
주소뒤에 ?term=지울단어   로 테스트 해보세용
문제없다면 이슈 닫기 부탁드립니다
