### ISSUE TITLE
fix: 웹뷰 카카오 oauth 리다이렉트 에러

### ISSUE THREAD

**Issue by zxcv2987** [woomae/copet#77]
### 🐞 Description
get v1/kakao/auth api호출 후 링크를 탈취하여 웹뷰에 띄움 -> 로그인 완료 후 리다이렉트 되야하는 시점에 에러 발생

headers: {sec-ch-ua: "Chromium";v="124", "Android WebView";v="124", "Not-A.Brand";v="99", sec-ch-ua-mobile: ?1, Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7, Upgrade-Insecure-Requests: 1, sec-ch-ua-platform: "Android", User-Agent: Mozilla/5.0 (Linux; Android 12; SM-G975N Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36, Referer: https://logins.daum.net/}, isRedirect: false, method: GET, hasGesture: false, isForMainFrame: true, url: https://kauth.kakao.com/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fdev.copet.life%2Fauth%2Fkakao%2Fcallback&through_account=true&client_id=190cb40d2822687a6a0968fee67ea093&stln=true

### 🧐 How to Solve?
백엔드에 문의 후 오류 메세지를 통해 트래킹 중

### 👥 Assignees
@woomae 
@zxcv2987 
_<sub>('@사용자명' 을 통해 해당 버그를 수정할 사람을 태그해 보세요.)</sub>_

**Comment by woomae** [comment]
**백엔드 서버 환경변수 변경**
